### ISSUE TITLE
Part number doesn't have to match exactly

### ISSUE THREAD

**Issue by dennevi** [beischer/netconv#4]
If the TinyCAD netlist has a component with a part number which is part of another part number, netconv will use that part number.

As an example:
Say the footprint map file has one row which says: 
HMR502/22k1     HM-0603

If the TinyCAD netlist has a component with product number HMR502/22k, the HM-0603 footprint will be used and no error will be shown in the log.

I'm not sure what happens if the footprint map file has both part numbers with different footprints. Most likely the first one found will be used.
HMR502/22k1     HM-0603
HMR502/22k       HM-0805
In this case most likely the HM-0603 footprint will be used for HMR502/22k, not HM-0805.

**Comment by beischer** [comment]
Bug confirmed.

**Comment by beischer** [comment]
Resolved in 1.6.1
e8465a43b84007a6b98420600e719bb6695b6e08
